// All CREATE TABLE statements. Run in order on boot — safe to re-run (IF NOT EXISTS everywhere).
module.exports = [
  `CREATE TABLE IF NOT EXISTS pay_scales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    rounding_rule TEXT NOT NULL DEFAULT 'round_down',
    hard_floor_ppw REAL NOT NULL DEFAULT 3.20,
    active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS pay_scale_tiers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pay_scale_id INTEGER NOT NULL REFERENCES pay_scales(id),
    net_ppw_threshold REAL NOT NULL,
    dollar_per_kw REAL NOT NULL,
    sort_order INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS reps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    full_name TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    display_name TEXT,
    rep_type TEXT NOT NULL DEFAULT 'closer',
    email TEXT,
    phone TEXT,
    account_info TEXT,
    pay_type TEXT NOT NULL DEFAULT 'commission',
    weekly_amount REAL,
    pay_scale_id INTEGER REFERENCES pay_scales(id),
    active INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS payroll_staff (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    full_name TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    staff_type TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    account_info TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    rep_id INTEGER REFERENCES reps(id),
    staff_id INTEGER REFERENCES payroll_staff(id),
    must_change_password INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_login_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS installers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    rate_per_watt REAL,
    m1_pct REAL,
    m2_pct REAL,
    notes TEXT,
    active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS financiers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    min_fico INTEGER,
    notes TEXT,
    active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS deal_statuses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    label TEXT NOT NULL UNIQUE,
    phase TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS commission_settings (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    default_pay_split REAL NOT NULL DEFAULT 0.50,
    referral_pay_split REAL NOT NULL DEFAULT 0.75,
    setter_split_pct REAL NOT NULL DEFAULT 0.35,
    closer_split_pct REAL NOT NULL DEFAULT 0.65,
    cashback_split_pct REAL NOT NULL DEFAULT 0.50,
    closer_clawback_pct_pss_socal REAL NOT NULL DEFAULT 0.20,
    owner_etai_m1 REAL NOT NULL DEFAULT 500,
    owner_etai_m2 REAL NOT NULL DEFAULT 500,
    owner_noy_m1 REAL NOT NULL DEFAULT 500,
    owner_noy_m2 REAL NOT NULL DEFAULT 500,
    joey_weekly_salary REAL NOT NULL DEFAULT 875,
    joey_tier1_max REAL NOT NULL DEFAULT 4.74,
    joey_tier1_amt REAL NOT NULL DEFAULT 150,
    joey_tier2_max REAL NOT NULL DEFAULT 5.99,
    joey_tier2_amt REAL NOT NULL DEFAULT 200,
    joey_tier3_amt REAL NOT NULL DEFAULT 300,
    austin_base REAL NOT NULL DEFAULT 6000,
    austin_rate_per_kw REAL NOT NULL DEFAULT 55
  )`,
  `CREATE TABLE IF NOT EXISTS deals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_name TEXT NOT NULL,
    customer_address TEXT,
    customer_phone TEXT,
    status_id INTEGER REFERENCES deal_statuses(id),
    closer_rep_id INTEGER REFERENCES reps(id),
    setter_rep_id INTEGER REFERENCES reps(id),
    pay_split REAL NOT NULL DEFAULT 0.50,
    is_referral INTEGER NOT NULL DEFAULT 0,
    installer_id INTEGER REFERENCES installers(id),
    financier_id INTEGER REFERENCES financiers(id),
    module_type TEXT,
    battery_type TEXT,
    num_batteries INTEGER,
    system_size_kw REAL,
    panel_count INTEGER,
    panel_watts REAL,
    annual_production_kwh REAL,
    contract_value REAL,
    epc_rate_per_watt REAL,
    monthly_payment REAL,
    rate_per_kwh REAL,
    escalator_pct REAL,
    cashback_amount REAL NOT NULL DEFAULT 0,
    date_signed TEXT,
    install_date TEXT,
    install_completed_date TEXT,
    ntp_approved_date TEXT,
    m1_approved_date TEXT,
    m1_paid_date TEXT,
    pto_granted_date TEXT,
    m2_approved_date TEXT,
    m2_paid_date TEXT,
    net_ppw REAL,
    pay_scale_rate REAL,
    rep_pool REAL,
    closer_pay_gross REAL,
    closer_pay_net REAL,
    setter_pay REAL,
    owner_etai_total REAL,
    owner_etai_m1_amount REAL,
    owner_etai_m2_amount REAL,
    owner_noy_total REAL,
    owner_noy_m1_amount REAL,
    owner_noy_m2_amount REAL,
    joey_m1_bonus REAL,
    joey_m2_bonus REAL,
    gross_amount REAL,
    expected_m1_amount REAL,
    expected_m2_amount REAL,
    funds_pending_m1 REAL,
    funds_pending_m2 REAL,
    funds_received_m1 REAL,
    funds_received_m1_date TEXT,
    funds_received_m2 REAL,
    funds_received_m2_date TEXT,
    funding_status TEXT,
    funding_status_override TEXT,
    -- Purely a reference number Joy can compare against the live calculator — never read by
    -- recalculate() or any other formula, by design.
    original_estimate_amount REAL,
    -- Plain manual deductions, same treatment as cashback_amount — feed into the Calculator's
    -- Total display but are never computed or locked, always Joy's own entry.
    advance_deduction REAL,
    deduction_other REAL,
    below_floor INTEGER NOT NULL DEFAULT 0,
    closer_paid INTEGER NOT NULL DEFAULT 0,
    closer_paid_date TEXT,
    setter_paid INTEGER NOT NULL DEFAULT 0,
    setter_paid_date TEXT,
    owner_etai_m1_paid INTEGER NOT NULL DEFAULT 0,
    owner_etai_m1_paid_date TEXT,
    owner_etai_m2_paid INTEGER NOT NULL DEFAULT 0,
    owner_etai_m2_paid_date TEXT,
    owner_noy_m1_paid INTEGER NOT NULL DEFAULT 0,
    owner_noy_m1_paid_date TEXT,
    owner_noy_m2_paid INTEGER NOT NULL DEFAULT 0,
    owner_noy_m2_paid_date TEXT,
    joey_m1_paid INTEGER NOT NULL DEFAULT 0,
    joey_m1_paid_date TEXT,
    joey_paid INTEGER NOT NULL DEFAULT 0,
    joey_paid_date TEXT,
    austin_paid INTEGER NOT NULL DEFAULT 0,
    austin_paid_date TEXT,
    closer_breakdown_approved INTEGER NOT NULL DEFAULT 0,
    closer_approved_at TEXT,
    closer_approved_by INTEGER REFERENCES users(id),
    setter_breakdown_approved INTEGER NOT NULL DEFAULT 0,
    setter_approved_at TEXT,
    setter_approved_by INTEGER REFERENCES users(id),
    manual_override INTEGER NOT NULL DEFAULT 0,
    overridden_fields TEXT NOT NULL DEFAULT '[]',
    field_override_reasons TEXT NOT NULL DEFAULT '{}',
    override_reason TEXT,
    override_by INTEGER REFERENCES users(id),
    override_at TEXT,
    admin_notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    created_by INTEGER REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS deal_adders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id INTEGER NOT NULL REFERENCES deals(id),
    label TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'misc',
    amount REAL NOT NULL DEFAULT 0,
    counts_as_hard_cost INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0
  )`,
  // Kept in its own table (not a column on deals) so the file's bytes are never accidentally
  // pulled along by a "SELECT d.*" — getDeal()/listDeals() would otherwise drag the whole file
  // into every single deal fetch and the Board's full list, which is exactly the kind of thing
  // that makes a page slow without anyone noticing why.
  `CREATE TABLE IF NOT EXISTS deal_estimate_files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id INTEGER NOT NULL REFERENCES deals(id),
    -- 'estimate' or 'final' — one file per deal per slot, replacing whichever was there before.
    slot TEXT NOT NULL DEFAULT 'estimate',
    file_name TEXT NOT NULL,
    file_type TEXT,
    file_size INTEGER NOT NULL,
    file_data BLOB NOT NULL,
    uploaded_at TEXT NOT NULL DEFAULT (datetime('now')),
    uploaded_by INTEGER REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS advances (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    rep_id INTEGER NOT NULL REFERENCES reps(id),
    deal_id INTEGER REFERENCES deals(id),
    amount REAL NOT NULL,
    date_sent TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    amount_deducted REAL NOT NULL DEFAULT 0,
    date_deducted TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS clawbacks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    deal_id INTEGER REFERENCES deals(id),
    rep_id INTEGER NOT NULL REFERENCES reps(id),
    total_clawback REAL NOT NULL,
    rep_share REAL NOT NULL,
    pwrd_share REAL NOT NULL,
    deducted INTEGER NOT NULL DEFAULT 0,
    deducted_date TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    table_name TEXT NOT NULL,
    record_id INTEGER NOT NULL,
    field_name TEXT,
    old_value TEXT,
    new_value TEXT,
    changed_by INTEGER REFERENCES users(id),
    changed_at TEXT NOT NULL DEFAULT (datetime('now')),
    reason TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    sid TEXT PRIMARY KEY,
    sess TEXT NOT NULL,
    expires INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS dropdown_options (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL,
    value TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS referral_bonuses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    referring_rep_id INTEGER NOT NULL REFERENCES reps(id),
    referred_rep_id INTEGER REFERENCES reps(id),
    referred_name TEXT,
    join_date TEXT,
    first_install_date TEXT,
    first_install_deal TEXT,
    amount REAL NOT NULL DEFAULT 1000,
    date_paid TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  `CREATE TABLE IF NOT EXISTS pay_runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pay_period_date TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    created_by INTEGER REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS pay_run_deals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pay_run_id INTEGER NOT NULL REFERENCES pay_runs(id),
    deal_id INTEGER NOT NULL REFERENCES deals(id),
    include_closer INTEGER NOT NULL DEFAULT 0,
    include_setter INTEGER NOT NULL DEFAULT 0,
    include_etai INTEGER NOT NULL DEFAULT 0,
    include_noy INTEGER NOT NULL DEFAULT 0,
    include_joey_m1 INTEGER NOT NULL DEFAULT 0,
    include_joey INTEGER NOT NULL DEFAULT 0,
    include_austin INTEGER NOT NULL DEFAULT 0,
    austin_kw_override REAL
  )`,
  `CREATE TABLE IF NOT EXISTS pay_run_adhoc (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pay_run_id INTEGER NOT NULL REFERENCES pay_runs(id),
    recipient_name TEXT NOT NULL,
    rep_id INTEGER REFERENCES reps(id),
    staff_id INTEGER REFERENCES payroll_staff(id),
    amount REAL NOT NULL,
    notes TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS pay_run_approvals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pay_run_id INTEGER NOT NULL REFERENCES pay_runs(id),
    approval_date TEXT NOT NULL,
    status TEXT NOT NULL,
    approved_by TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`
];
